import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { call, getUser } from '../../api';
import { ActionBar } from '../../ui/ActionBar';
import { Button } from '../../ui/Button';
import { Card } from '../../ui/Card';
import { Money, Num } from '../../ui/Money';
import { PageHeader } from '../../ui/PageHeader';
import { StatusChip } from '../../ui/StatusChip';
import { Bar, Funnel, Preview } from './charts';
// Row actions come from each module's `actions` command; only names and labels live here.
const approval = {
    requisition: { module: 'intake', noun: 'Requisition', labels: { approve: 'Approve requisition', reject: 'Reject requisition' } },
    award: { module: 'awards', noun: 'Award', labels: { approved: 'Approve award', rejected: 'Reject award' } },
};
const title = 'text-section font-semibold';
export function Dashboard() {
    const q = useQuery({ queryKey: ['dashboard', getUser()], queryFn: () => call('reporting', 'dashboard') });
    if (q.error)
        return _jsx(Card, { className: "text-danger", role: "alert", children: q.error.message });
    if (!q.data)
        return _jsx("div", { "aria-busy": true, className: "h-80 animate-pulse rounded-hero bg-primary-soft" });
    const d = q.data;
    const waiting = d.myApprovals.length;
    return (_jsxs("div", { className: "grid gap-6", children: [_jsx(PageHeader, { title: "Project dashboard", chip: _jsxs(_Fragment, { children: [_jsx(StatusChip, { tone: d.audit.ok ? 'success' : 'danger', children: d.audit.ok ? 'Audit chain verified' : 'Audit chain broken' }), d.atRisk.length > 0 && _jsxs(StatusChip, { tone: "warning", children: [d.atRisk.length, " package", d.atRisk.length > 1 ? 's' : '', " at risk"] })] }), figures: [
                    { label: 'Value in pipeline', big: true, value: _jsx(Money, { value: d.valueInPipeline, animate: true }) },
                    { label: 'Saved against estimate', value: _jsx(Money, { value: d.savings.saved, animate: true }) },
                    { label: 'Long-lead packages', value: _jsx(Num, { value: d.longLead, animate: true }) },
                ], action: _jsxs("div", { className: "flex items-center gap-3 max-md:flex-col max-md:items-stretch", children: [!waiting && _jsx("span", { className: "text-on-hero-soft", children: "Nothing is waiting on you" }), _jsx(Button, { variant: "primary", disabled: !waiting, onClick: () => document.getElementById('my-actions')?.scrollIntoView({ behavior: 'smooth' }), children: "Review actions" })] }), visual: _jsx(Preview, { d: d }) }), _jsxs("div", { className: "relative z-10 -mt-14 grid gap-6 px-1 md:px-6 lg:grid-cols-3", children: [_jsxs(Card, { i: 1, lift: true, className: "grid content-start gap-3", children: [_jsx("h2", { className: title, children: "Pipeline" }), _jsx("p", { className: "text-ink-soft", children: "Packages reaching each stage" }), _jsx(Funnel, { ...d.pipeline })] }), _jsxs(Card, { i: 2, lift: true, className: "grid content-start gap-3", children: [_jsx("h2", { className: title, children: "Savings" }), _jsx("p", { className: "text-ink-soft", children: "Awarded value against the estimate" }), _jsx(Bar, { label: "Estimate", value: d.savings.baseline, max: d.savings.baseline, tone: "bg-peri" }), _jsx(Bar, { label: "Awarded", value: d.savings.awarded, max: d.savings.baseline, tone: "bg-primary" }), _jsxs("p", { className: title, children: ["Saved ", _jsx(Money, { value: d.savings.saved, animate: true, className: "text-success" })] })] }), _jsxs(Card, { i: 3, lift: true, className: "grid content-start gap-3", children: [_jsx("h2", { className: title, children: "At risk" }), d.atRisk.length === 0 && _jsx("p", { className: "text-ink-soft", children: "Every open package has float." }), _jsx("ul", { className: "grid gap-3", children: d.atRisk.map(r => (_jsxs("li", { className: "grid gap-1", children: [_jsx("span", { className: "font-medium", children: r.title }), _jsxs("span", { className: "flex flex-wrap items-center gap-2", children: [_jsx(StatusChip, { tone: r.health === 'late' ? 'danger' : 'warning', children: r.health.replace('_', ' ') }), _jsxs("span", { className: "text-ink-soft", children: [_jsx("span", { className: "font-code", children: r.id }), ", float ", _jsx(Num, { value: r.floatDays, className: "font-semibold text-ink" }), " days"] })] })] }, r.id))) })] })] }), _jsxs("div", { className: "grid gap-6 px-1 md:px-6 lg:grid-cols-[3fr_2fr]", children: [_jsxs(Card, { id: "my-actions", i: 4, className: "scroll-mt-4", children: [_jsx("h2", { className: title, children: "My actions" }), waiting === 0 && _jsx("p", { className: "mt-2 text-ink-soft", children: "Nothing is waiting on you. Switch role in the top bar to see another queue." }), _jsx("ul", { className: "mt-3 divide-y divide-line", children: d.myApprovals.map(a => {
                                    const k = approval[a.type];
                                    return (_jsxs("li", { className: "grid gap-3 py-4 md:grid-cols-[1fr_auto] md:items-center", children: [_jsxs("div", { children: [_jsxs("p", { className: "font-medium", children: [k.noun, " ", _jsx("span", { className: "font-code", children: a.id })] }), _jsx(Money, { value: a.value, className: "text-ink-soft" })] }), _jsx(ActionBar, { module: k.module, id: a.id, labels: k.labels, run: (act, reason) => call(k.module, 'decide', a.id, act, reason) })] }, a.id));
                                }) })] }), _jsxs(Card, { i: 5, children: [_jsx("h2", { className: title, children: "Expiring documents" }), d.expiringDocs.length === 0 && _jsx("p", { className: "mt-2 text-ink-soft", children: "No supplier document expires within 30 days." }), _jsx("ul", { className: "mt-3 divide-y divide-line", children: d.expiringDocs.map(x => (_jsxs("li", { className: "grid gap-1 py-3", children: [_jsx("span", { className: "font-medium", children: x.supplier }), _jsxs("span", { className: "flex flex-wrap items-center gap-2", children: [_jsx(StatusChip, { tone: x.expired ? 'danger' : 'warning', children: x.expired ? 'Expired' : 'Expiring' }), _jsxs("span", { className: "text-ink-soft", children: [x.doc.replace('_', ' '), ", ", _jsx("span", { className: "font-code", children: x.expires })] })] })] }, x.supplier + x.doc))) })] })] }), _jsxs("details", { open: true, className: "px-1 md:px-6", children: [_jsx("summary", { className: `${title} cursor-pointer rounded-ctl px-1 py-2`, children: "Budget by cost code" }), _jsx(Card, { i: 6, className: "mt-2 grid gap-4", children: d.budget.map(b => (_jsxs("div", { className: "grid gap-1 md:grid-cols-[8rem_1fr_14rem] md:items-center md:gap-4", children: [_jsxs("span", { className: "font-code", children: [b.project, " ", b.costCode] }), _jsx(Bar, { value: b.committed, max: b.budget, tone: "bg-primary" }), _jsxs("span", { className: "text-ink-soft md:text-right", children: [_jsx(Money, { value: b.available, className: "font-semibold text-ink" }), " free"] })] }, b.project + b.costCode))) })] })] }));
}
